---
site_name: My Digital Complex
site_url: https://alohamujeeb.github.io/
extra:
  generator: false #Disable footer with "Made with Material for MkDocs" message

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
      
  - admonition
  - pymdownx.details

theme:
  name: material
  #custom_dir: docs/overrides

  font:
    #code: Roboto Mono
    #text: Inconsolata
    #text: Anonymous Pro  
    text: Roboto Mono  
    code: Source Code Pro 
    
  palette:
    #scheme: default
    #primary: default
    #accent: default
    
    # Palette toggle for light mode
    - scheme: default
      #primary: indigo
      primary:  blue grey
      accent: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      #primary: indigo
      primary: blue grey
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
        
  features:
    - navigation.tracking
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs # to display menu in the top bar
    - navigation.tabs.sticky 
    - navigation.footer #next and previous buttons
    - navigation.indexes
    - navigation.sections
    #- navigation.expand
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - header.autohide
    - navigation.prune 
    - navigation.indexes 
    - toc.follow
    #- toc.integrate  #do it at runtime later
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share


plugins: 
  - offline
  - tags
  - blog:
      blog_dir: blog
      blog_toc: true
      categories_allowed:
        - 5G
        - Embedded Systems
        - Robotics
        - ROS2
        - OpenRMF
        - RMF
        - Linux
        - Programming
        - Life experiences
  - search
  - meta
  - exclude-search:
      exclude:
        - documentation/*
  
        
# Page tree
nav:
  - Home-&-Find:
    - My Digital Complex: index.md
    - About Me: about/aboutme.md
    - Contact Info: about/contact.md
    - ====Search====:
      - Keywords/Tags: tags.md
    - ====Updates====: 
      - Whats New: whatsnew.md
    - ===Reference Bits===:
      - emojis-list: emoji-list.md
    
      
  - Linux-&-Networking:
    - index: linux/index.md
    - ==== Bash Shell====:
      - bash shell: linux/cli-bash/index.md
      - Linux Commands Reference: linux/cli-bash/linux-cli.md
      - Bash Scripting: linux/cli-bash/bash.md
    - ===Linux Networking===: 
      - Linux Networking: linux/linux-networking/index.md
      - NAT(Part-1): linux/linux-networking/nat1.md
      - NAT(Part-2): linux/linux-networking/nat2.md
      - Linux Firewall: linux/linux-networking/linux-firewall.md
      - Modem Manager: linux/linux-networking/modem-manager.md
    - ====Protocls====:
      - Protocols: linux/protocols/index.md    
      - QUIC: linux/protocols/quic.md
    
    
  #- RoboEmbed
  #- WebCraft  
  - Programming: 
    - Programming: programming/index.md
    - ====Languages====: 
      - languages: programming/languages/index.md
      - Golang 101 (Basics):
        - Go101: programming/languages/golang101/index.md
        - 01-Getting Started: programming/languages/golang101/01-gettingstarted.md
        - 02-Some Fundamentals: programming/languages/golang101/02-basics.md
        - 03a-Data Types- Part 1: programming/languages/golang101/03a-datatypes-1.md
        - 03b-Data Types- Part 2: programming/languages/golang101/03b-datatypes-2.md
        - 04-Operators and Typecasting: programming/languages/golang101/04-operators.md
        - 05-Conditions and Loops:  programming/languages/golang101/05-if-loops.md
        - 06a-Functions- Part 1: programming/languages/golang101/06a-functions-in-Go-P1.md
        - 06b-Functions- Part 2: programming/languages/golang101/06b-functions-in-Go-P2.md
        - 07-Pointer in Go: programming/languages/golang101/07-pointer-in-Go.md
        - 08-Panic & Recover: programming/languages/golang101/08-panic-in-Go.md
        - 09-Arrays in Go: programming/languages/golang101/09-arrays-in-Go.md
        - 10-Slices in Go: programming/languages/golang101/10-slices-in-Go.md
         #- imports and packages
        #- Collections 
      - Golang 102 (Concurrency):
        - Go102: programming/languages/golang102conc/index.md
        - 01-Concurrency in Go: programming/languages/golang102conc/01-goroutines.md
        
      - Golang 201 (Intermediate):
        - Go201: programming/languages/golang201/index.md
        - 01-Modules in Go: programming/languages/golang201/01-modules.md
        
      - Rust 101 (Common Concepts):
        - Rust101: programming/languages/rust101/index.md
        - 01-Getting Started: programming/languages/rust101/01-gettingstarted.md
      - Rust 201 (Intermediate RUST):
        - index: programming/languages/rust201/index.md
      - Python References: 
        - Python References: programming/languages/python/index.md
        - Python Env: programming/languages/python/python-env.md
        
    - ===Frameworks/Libs===:
      - frameworks: programming/frameworks/index.md    
      - QUIC-GO 101: 
        - index: programming/frameworks/quicgo101/index.md
        - Hello World (in Go): programming/frameworks/quicgo101/01-hello-world.md
        - Hello World (in Python): programming/frameworks/quicgo101/01-hello-world-python-quic.md

  - SW-Eng:  
    - index: sweng/index.md  
    - ===Containers====:
      - containers: sweng/containers/index.md
      - Docker 101:
        - docker101: sweng/containers/docker101/index.md
        - Docker-Getting Started: sweng/containers/docker101/01-getting-started.md
        - Hello-Docker: sweng/containers/docker101/02-docker-hello.md
        - A Network Example: sweng/containers/docker101/03-docker-network-example.md
        - A Multi-Client Example: sweng/containers/docker101/04-tcp-example.md
        - Docker Quick Reference: sweng/containers/docker101/docker-network-commands.md
    - ===CI/CD====:
      - cicd: sweng/cicd/index.md

  - Robotics-&-EmbSys: 
    - index:  embsys-drobot/index.md
    - ===Modems(5G)===:
      - modems: embsys-drobot/modems/index.md
      - Quectel RM530N-GL: 
        - RM530N-GL: embsys-drobot/modems/Quectel-RM530N-GL/index.md
        - Hardware Setup: embsys-drobot/modems/Quectel-RM530N-GL/01-hw-setup-pi5.md
        - Software Setup: embsys-drobot/modems/Quectel-RM530N-GL/02-sw-setup-pi5.md
        - AT Command Reference: embsys-drobot/modems/Quectel-RM530N-GL/03-at-commands.md
        #- Mobilensight Tool: embsys-drobot/Quectel-RM530N-GL/04-mobile-insight.md
    - ===Platforms===:
      - Platforms: embsys-drobot/platforms/index.md
      - Raspberry-Pi 5: embsys-drobot/platforms/pi5/index.md
    - ====ROS====:
      - ROS2: embsys-drobot/ros/index.md
      - Pub/Sub:
        - pub/sub model: embsys-drobot/ros/pubsub-model.md
    - ====RMF====:     
      - OpenRMF: embsys-drobot/openrmf/index.md
        
  - Blogs:
    - blog/index.md
 