---
site_name: Mujeeb's Digital World
site_url: https://alohamujeeb.github.io/
extra:
  generator: false # Disable footer with "Made with Material for MkDocs" message
  mathjax: true
    
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

  - admonition
  - pymdownx.details

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  
theme:
  name: material
  #custom_dir: docs/overrides
 

  font:
    #code: Roboto Mono
    #text: Inconsolata
    #text: Anonymous Pro  
    text: Roboto Mono  
    code: Source Code Pro 
    
  palette:
    #scheme: default
    #primary: default
    #accent: default

    # Palette toggle for light mode
    - scheme: default
      #primary: indigo
      primary:  blue grey #teal
      accent: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - scheme: slate
      #primary: indigo
      primary: teal #lime #teal #blue grey
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  features:
    - navigation.tracking
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs # to display menu in the top bar
    - navigation.tabs.sticky 
    - navigation.footer #next and previous buttons
    - navigation.indexes
    - navigation.sections
    #- navigation.expand
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - header.autohide
    - navigation.prune 
    - navigation.indexes 
    - toc.follow
    #- toc.integrate  #do it at runtime later
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share


plugins: 
  - offline
  - tags
  - blog:
      blog_dir: blog
      blog_toc: true
      categories_allowed:
        - 5G
        - Embedded Systems
        - Robotics
        - ROS
        - Linux
        - Programming
        - Algorithms
        - Life experiences
        - Multimedia
        - Video
        - Artificial Intelligence
        - Machine Learning
        - Computer Networking
        - Streaming
  - search
  - meta
  - exclude-search:
      exclude:
        - documentation/*
  
        
# Page tree
nav:
  - Home:
    - Home: index.md
    - <font color='tomato'><h3>Design Notes</h3></font>: design/index.md
    - <font color='tomato'><h3>Developer Reference</h3></font>: references/index.md
    - <font color='green'><h3>Whispers of Heart</h3></font>: woh.md
    - <font color='green'><h3>My Inspiration</h3></font>: inspiration.md
    - <font color='green'><h3>Search</h3></font>: tags.md

  - Blogs:
    - blog/index.md
  
  #- Courses:
  #  - courses/index.md

 
