---
site_name: Mujeeb's Online Library
site_url: https://alohamujeeb.github.io/
extra:
  generator: false #Disable footer with "Made with Material for MkDocs" message

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details

  
theme:
  name: material
  #custom_dir: docs/overrides

  font:
    #code: Roboto Mono
    #text: Inconsolata
    text: Anonymous Pro  
    code: Source Code Pro 
    
  palette:
    #scheme: default
    #primary: default
    #accent: default
    
    # Palette toggle for light mode
    - scheme: default
      #primary: indigo
      primary:  blue grey
      accent: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      #primary: indigo
      primary: blue grey
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
        
  features:
    - navigation.tracking
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs # to display menu in the top bar
    - navigation.tabs.sticky 
    - navigation.footer #next and previous buttons
    - navigation.indexes
    - navigation.sections
    #- navigation.expand
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - header.autohide
    - navigation.prune 
    - navigation.indexes 
    - toc.follow
    #- toc.integrate  #do it at runtime later
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share


plugins: 
  - offline
  - tags
  - blog:
      blog_dir: blog
      blog_toc: true
      categories_allowed:
        - 5G
        - Embedded Systems
        - Robotics
        - ROS2
        - OpenRMF
        - RMF
        - Linux
        - Programming
        - Life experiences
  - search
  - meta
  - exclude-search:
      exclude:
        - documentation/*
  
        
# Page tree
nav:
  - Start-&-Info:
    - My Online Library: index.md
    - About Me: about/aboutme.md
    - Searching for something?:
      - Keywords/Tags: tags.md
    - Updates: 
      - Whats New: whatsnew.md
    - emojis-list: emoji-list.md
    
      
  - Linux-&-Networking:
    - index: linux/index.md
    - Linux CLI:
      - Linux Commands Reference: linux/linux-cli.md
    - Linux Scripting:
      - Bash Shell: linux/bash.md
    - Linux Networking: 
      - Networking Basics: linux/linux-networking.md
    - quic protocol: linux/quic.md
    
    
  #- RoboEmbed
  #- WebCraft  
  - Programming: 
    - index: programming/index.md
    - Languages: 
      - Golang 101 (Common Concepts):
        - index: programming/languages/golang101/index.md
        - 01-Getting Started: programming/languages/golang101/01-gettingstarted.md
        - 02-Some Fundamentals: programming/languages/golang101/02-basics.md
        - 03a-Data Types- Part 1: programming/languages/golang101/03a-datatypes-1.md
        - 03b-Data Types- Part 2: programming/languages/golang101/03b-datatypes-2.md
        - 04-Operators and Typecasting: programming/languages/golang101/04-operators.md
        - 05-Conditions and Loops:  programming/languages/golang101/05-if-loops.md
        - 06a-Functions- Part 1: programming/languages/golang101/06a-functions-in-Go-P1.md
        - 06b-Functions- Part 2: programming/languages/golang101/06b-functions-in-Go-P2.md
        - 07-Pointer in Go: programming/languages/golang101/07-pointer-in-Go.md
        - 08-Panic & Recover: programming/languages/golang101/08-panic-in-Go.md
        - 09-Arrays in Go: programming/languages/golang101/09-arrays-in-Go.md
        - 10-Slices in Go: programming/languages/golang101/10-slices-in-Go.md
        #- imports and packages
        #- Collections 
      - Golang 201 (Intermediate):
        - index: programming/languages/golang201/index.md
        - 01-Modules in Go: programming/languages/golang201/01-modules.md
        
      - Rust 101 (Common Concepts):
        - index: programming/languages/rust101/index.md
        - 01-Getting Started: programming/languages/rust101/01-gettingstarted.md
      - Rust 201 (Intermediate RUST):
        - index: programming/languages/rust201/index.md

    - Frameworks/Libs: 
      - QUIC-GO 101: 
        - index: programming/frameworks/quicgo101/index.md
        - Hello World (in Go): programming/frameworks/quicgo101/01-hello-world.md
        - Hello World (in Python): programming/frameworks/quicgo101/01-hello-world-python-quic.md

  - SW-Engineering:  
    - index: sweng/index.md  
    - Docker & Containers:
      - Docker 101:
        - index: sweng/docker101/index.md
        - Docker-Getting Started: sweng/docker101/getting-started.md
        - Hello-Docker: sweng/docker101/docker-hello.md
        - A Network Example: sweng/docker101/docker-network-example.md
        - A Multi-Client Example: sweng/docker101/tcp-example.md
        - Docker Quick Reference: sweng/docker101/docker-network-commands.md
            
  - Robotics-&-Embedded Systems: 
    - index:  embsys-drobot/index.md
    - Quectel:
      - Quectel RM530N-GL: 
        - index: embsys-drobot/Quectel-RM530N-GL/index.md
        - Mounting on Raspberry Pi: embsys-drobot/Quectel-RM530N-GL/RM530N_RPi_connections.md
        - AT Command Reference: embsys-drobot/Quectel-RM530N-GL/at-command-reference.md
    - Embedded Platforms:
      - Raspberry-Pi 5: 
        - index: embsys-drobot/pi5/index.md
    - ROS and RMF:
      - ROS2: 
        - index: embsys-drobot/ros/index.md
      - OpenRMF:
        - index: embsys-drobot/openrmf/index.md
        
  - Blogs:
    - blog/index.md
 